# What projectile catches the creature.
Projectile Catcher: EGG
# When throw or catch the creature, this shows an effect (like old MobCatcher)
Catcher Effect: true
# The time to release (spawn) the creature in seconds.
Release Time: 3
# Cost Mode: [ NONE, ITEM, VAULT, ALL ]
Cost Mode: ITEM
# When in ITEM or ALL mode, a player must have this item to catch a creature.
Cost Item: REDSTONE
Cost Amount: 1
# When in VAULT or ALL mode, a player must have at least this amount of money.
Cost Vault: 100
# In these worlds, you cannot capture or release creatures.
Disabled Worlds: []
# Should eggs take the color of the creature they belong to?
Colored Eggs: true
# Should we hook into Towny
Towny Hook: false
# Are you using GriefPrevention?
GriefPrevention Hook: false
# Are you using Residence (https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-13-1.11480/)?
Residence Hook: false
# If true, you can use custom flags to allow capture, if flag contains 'animal' has refereces a AnimalType and 'mob' or 'monster' is MonsterType
Residence Allow Flags: ["animalcapture","mobcapture","capture"]
# Allow capturing in Residences without allowed flags
Residence Allow Default: false
# Allow capturing creatures with melee
MeleeCapture: true
# Require projectile to contain key metadata.
Require Unique: false
# With '/mobcapture spawn', a projectile will be spawned with these values (only with Require Unique enabled).
Unique Display Name: '&6Mob Catcher'
Unique Lore:
  - '&3Shoot a mob with me!'